<?xml version="1.0"?>
<robot name="Strirus" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Import all Gazebo-customization elements, including Gazebo colors -->
	<xacro:include filename="$(find strirus_robot_description)/urdf/strirus.gazebo" />
	<!-- Import Rviz colors -->
	<xacro:include filename="$(find strirus_robot_description)/urdf/materials.xacro" />


	<xacro:property name="deg2rad" value="${pi / 180}" />
	<!-- Constants for simulating -->
	<!-- number of legs need to be real number - 1 (it is from one side only)-->
	<!-- Xacro arg provides xacro.py file.xacro real_number_of_legs:=12 -->
	<xacro:arg name="real_number_of_legs" default="6" />
	<xacro:arg name="angle_between_legs" default="60" />
	<!-- in degree -->
	<xacro:arg name="offset_between_legs_wave" default="0" />

	<xacro:property name="real_number_of_legs" value="$(arg real_number_of_legs)" />
	<xacro:property name="number_of_legs" value="${real_number_of_legs - 1}" />
	<xacro:property name="angle_between_legs" value="$(arg angle_between_legs)" />
	<!-- in degree -->
	<xacro:property name="offset_between_legs_wave" value="$(arg offset_between_legs_wave)" />


	<!-- Body and leg Constants -->
	<xacro:property name="body_x_offset" value="${0}" />
	<xacro:property name="body_y_offset" value="${body_length / 2}" />
	<xacro:property name="body_z_offset" value="${leg_width + leg_height}" />
	<xacro:property name="first_hole_x_offset" value="${0.05}" />	

	<xacro:property name="body_width" value="${0.5}" />
	<xacro:property name="body_height" value="${0.07}" />
	<!-- consider that body is hollow-type , 1200 is plastic density-->
	<xacro:property name="body_wall_thickness" value="0.01" />
	<xacro:property name="body_weight" value="${((body_width * body_length * body_height) - ((body_width - body_wall_thickness) * (body_length - body_wall_thickness) * (body_height - body_wall_thickness))) * 1200}"/>	

	<xacro:property name="leg_x_offset" value="${0}" />
	<xacro:property name="leg_y_offset" value="${0}" />
	<xacro:property name="leg_z_offset" value="${0}" />

	<xacro:property name="leg_x_offset_in_body" value="${-0.075}" />
	<xacro:property name="leg_width" value="${0.02}" />
	<xacro:property name="leg_height" value="${0.08}" />
	<xacro:property name="fallibility_between_legs" value="${0.002 + 2 * leg_width}" />

	<!-- Formulas -->
	<xacro:property name="dist_between_legs" value="${leg_height * sin(angle_between_legs * deg2rad) + fallibility_between_legs}" />
	<xacro:property name="body_length" value="${2 * first_hole_x_offset + (real_number_of_legs -1) * dist_between_legs}" />


	<!-- Leg description -->
	<xacro:macro name="leg" params="prefix num side">
	<xacro:property name="angle_coeff_left" value="${(offset_between_legs_wave + angle_between_legs * num) % 360 * deg2rad}" />
	<xacro:property name="angle_coeff_right" value="${-(angle_between_legs * num) % 360 * deg2rad}" />
		<link name="leg_${prefix}_${num}">
			<inertial>
				<!-- was calcuclated in Siemens NX -->
				<mass value="0.36"/>
				<xacro:if value="${prefix == 'left'}">
					<origin rpy="${angle_coeff_left} 0 0" xyz="${leg_x_offset + (0.1)} ${leg_y_offset + ((-2.99e-7 * cos(angle_coeff_left)) - (-0.04 * sin(angle_coeff_left)))} ${leg_z_offset + ( - (-2.99e-7 * sin(angle_coeff_left)) + (-0.04 * cos(angle_coeff_left)))}"/>
				</xacro:if>
				<xacro:if value="${prefix == 'right'}">
					<origin rpy="${angle_coeff_right} 0 0" xyz="-${leg_x_offset + (0.1)} ${-(leg_y_offset + ((-2.99e-7 * cos(angle_coeff_right)) - (-0.04 * sin(angle_coeff_right))))} ${leg_z_offset + ( - (-2.99e-7 * sin(angle_coeff_right)) + (-0.04 * cos(angle_coeff_right)))}"/>
				</xacro:if>
				<inertia ixx="0.0009" ixy="0" ixz="-0.0019" iyy="0.0053" iyz="0" izz="0.0044"/>
				<!-- <inertia ixx="0.000" ixy="0" ixz="0.00" iyy="0.00" iyz="0" izz="0.00"/> -->
			</inertial>
			<collision>
				<!-- legs wave offset change only on the left side -->
				<xacro:if value="${prefix == 'left'}">
					<origin rpy="${angle_coeff_left} 0 0" xyz="${leg_x_offset} ${leg_y_offset} ${leg_z_offset}"/>
				</xacro:if>
				<xacro:if value="${prefix == 'right'}">
					<origin rpy="${angle_coeff_right} 0 ${pi}" xyz="${leg_x_offset} ${leg_y_offset} ${leg_z_offset}"/>
				</xacro:if>
				<geometry>
					<mesh filename="package://strirus_robot_description/meshes/stl/leg_30_degree.stl" scale="1.0 1.0 1.0"/>
				</geometry>



			</collision>
			<visual>
				<xacro:if value="${prefix == 'left'}">
					<origin rpy="${(offset_between_legs_wave + angle_between_legs * num) % 360 * deg2rad} 0 0" xyz="${leg_x_offset} ${leg_y_offset} ${leg_z_offset}"/>
				</xacro:if>
				<xacro:if value="${prefix == 'right'}">
					<origin rpy="${-(angle_between_legs * num) % 360 * deg2rad} 0 ${pi}" xyz="${leg_x_offset} ${leg_y_offset} ${leg_z_offset}"/>
				</xacro:if>
				<geometry>
					<mesh filename="package://strirus_robot_description/meshes/stl/leg_30_degree.stl" scale="1.0 1.0 1.0"/>
				</geometry>
				<material name="blue"/>
			</visual>
		</link>
		<!-- /////////////// -->
		<joint name="leg_${prefix}_${num}_revolute_joint" type="revolute">
			<parent link="body"/>
			<child link="leg_${prefix}_${num}"/>
			<origin rpy="0       0      0" xyz="${(body_width / 4 + leg_x_offset_in_body) * side} ${first_hole_x_offset + (num) * dist_between_legs}  ${body_z_offset}"/>
			<axis xyz="1 0  0"/>
			<limit effort="-1" lower="-1e+100" upper="1e+100" velocity="-1"/>
			<joint_properties damping="0.0" friction="0.0" />

		</joint>

		<!-- /////////////// -->
<!-- 		<transmission name="leg_${prefix}_${num}_transmission">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="leg_${prefix}_${num}_revolute_joint">
				<hardwareInterface>VelocityJointInterface</hardwareInterface>
			</joint>
			<actuator name="leg_${prefix}_0_actuator">
				<hardwareInterface>VelocityJointInterface</hardwareInterface>
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
		</transmission> -->

	  <gazebo reference="leg_${prefix}_${num}">
    <material>Gazebo/Gray</material>
  </gazebo>

	</xacro:macro>

	<!-- Body description -->
	<link name="base_link"/>
	<joint name="base_link_body_fixed" type="fixed">
		<parent link="base_link"/>
		<child link="body"/>
	</joint>
	<!-- /////////////// -->
	<link name="body">
		<inertial>
			<!-- 250 value is mass density, the value is just empiric-->
			<mass value="${body_weight}"/>
			<origin rpy="0  0  0" xyz="${body_x_offset} ${body_y_offset}  ${body_z_offset}"/>
			<!-- consider that box is hollow-type (inertia *1.2)-->
			<inertia 
				ixx="${1/12 * body_weight * (body_height * body_height + body_length * body_length) * 1.2}"  ixy="0"  ixz="0" 
				iyy="${1/12 * body_weight * (body_height * body_height + body_width * body_width) * 1.2}" iyz="0" 
				izz="${1/12 * body_weight * (body_length * body_length + body_width * body_width) * 1.2}" />
<!--				<inertia ixx="0.000" ixy="0" ixz="0" iyy="0.000" iyz="0" izz="0.000"/> -->
			</inertial>
			<collision >
				<origin rpy="0  0  0" xyz="${body_x_offset} ${body_y_offset}  ${body_z_offset}"/>
				<geometry>
					<box size="${body_width / 2} ${body_length} ${body_height / 2}"/>
				</geometry>
			</collision>
			<visual >
				<origin rpy="0  0  0" xyz="${body_x_offset} ${body_y_offset}  ${body_z_offset}"/>
				<geometry>
					<box size="${body_width / 2} ${body_length} ${body_height / 2}"/>
				</geometry>
				<material name="green"/>
			</visual>
		</link>

		<gazebo reference="body">
    		<material>Gazebo/DarkYellow</material>
  		</gazebo>
		
		<!-- create needed number of legs (is implemented by recurcion) -->
		<xacro:macro name="create_legs" params="prefix side number">
			<xacro:leg prefix="${prefix}" num="${number}" side="${side}"/>
			<xacro:if value="${number}">
				<xacro:create_legs number="${number-1}" prefix="${prefix}" side="${side}"/>
			</xacro:if>
		</xacro:macro>


		<xacro:create_legs prefix="left" side="1" number="${number_of_legs}" />
		<xacro:create_legs prefix="right" side="-1" number="${number_of_legs}" />


		<gazebo>

			<xacro:macro name="create_gearbox_joints_between_legs" params="prefix side number">
				<joint name="legs_${prefix}_0_${number}_gearbox_joint" type="gearbox">
					<parent>leg_${prefix}_0</parent>
					<child>leg_${prefix}_${number}</child>
					<gearbox_ratio>-1</gearbox_ratio>
					<gearbox_reference_body>base_link</gearbox_reference_body>
					<axis>
						<xyz>1.000000 0.000000 0.000000</xyz>
						<use_parent_model_frame>true</use_parent_model_frame>
					</axis>
					<axis2>
						<xyz>1.000000 0.000000 0.000000</xyz>
						<use_parent_model_frame>true</use_parent_model_frame>
					</axis2>
				</joint>

				<xacro:if value="${number - 1}">
					<xacro:create_gearbox_joints_between_legs number="${number-1}" prefix="${prefix}" side="${side}"/>
				</xacro:if>
			</xacro:macro>

			<xacro:create_gearbox_joints_between_legs prefix="left" side="1" number="${number_of_legs}" />
			<xacro:create_gearbox_joints_between_legs prefix="right" side="-1" number="${number_of_legs}" />
		</gazebo>

		
</robot>